app/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path
from app import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("menu/", include("goods.urls", namespace="menu")),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goods/urls.py
from django.urls import path

from goods import views

app_name = "goods"  # для подгрузки файлов из папки main

urlpatterns = [
    path('', views.menu, name='menu'),
    path('product/<slug:product_slug>/', views.product, name='product'),

    
]

main/urls.py
from django.urls import path

from main import views

app_name = "main"  # для подгрузки файлов из папки main

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('cart/', views.cart, name='cart'),

    
]

cart/models.py
from django.db import models

# Create your models here.

goods/models.py
from django.db import models


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name="Название")
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name="URL")
    
    class Meta:
        db_table = 'category'
        verbose_name = "Категори"
        verbose_name_plural = "Категории"
        
    def __str__(self) -> str:
        return self.name

    
class Product(models.Model):
    # удаляя категорию, мы удаляем все ее продукты
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE, verbose_name="Категория")
    name = models.CharField(max_length=150, unique=True, verbose_name="Название")
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name="URL")
    description = models.TextField(blank=True, null=True, verbose_name="Описание")
    image = models.ImageField(upload_to="goods_images", blank=True, null=True, verbose_name="Изображение")
    price = models.DecimalField(default=0, max_digits=7, decimal_places=0, verbose_name="Цена")
    discount = models.DecimalField(default=0, max_digits=4, decimal_places=0, verbose_name="Скидка в %")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")

    # когда был создан продукт
    created_at = models.DateTimeField(auto_now_add=True)
    
    # показываем новый продукт первым
    class Meta:
        db_table = 'product'
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        
    def __str__(self) -> str:
        return f"{self.name} Количество - {self.quantity}"
    
    # проверка на скидку
    def sell_price(self):
        if self.discount:
            return round(self.price - self.price*self.discount/100)
        
        return self.price
            
        

main/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render

# Create your views here.

goods/views.py
from django.shortcuts import render

from goods.models import Product

# Create your views here.


def menu(request):
    goods = Product.objects.all()
    context = {
        "title": "Меню",
        "goods": goods,
    }
    return render(request, "goods/menu.html", context)


def product(request, product_slug):
    product = Product.objects.get(slug=product_slug)


    context = {
        "product": product,
    }
    return render(request, "goods/product.html", context=context)

main/views.py
from django.shortcuts import render

from goods.models import Category


def index(request):
    
    context = {
        'title': "Главная",
        'welcome': "Добро пожаловать в Pizza House",
        'about': "Здесь, вы не сможете уйти с пустым желудком!",
    }
    return render(request, "main/index.html", context)



def contact(request):
    context = {
        'title': "Контакты",
        'about': "Свяжитесь с нами по телефону: 8800553535",
    }
    return render(request, "main/contact.html", context)

def cart(request):
    return render(request, "main/cart.html")

goods/templates/goods/menu.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}
{{title}}
{% endblock %}
{% block content %}
<div>
  <h1 class='text-3xl font-bold mb-5'>{{title}}</h1>
  <div>
    <ul class='m-0 p-0 list-none grid gap-5 grid-cols-auto  max-lg:grid-cols-2 max-md:grid-cols-1 '>
      {% for product in goods %}
      <li>
        <article class="flex flex-col w-full max-w-xs  bg-white hover:shadow-xl rounded-[50px]  h-full max-[425px]:w-full">
          <div class="mt-4 h-64  transition-transform hover:scale-110">
            {% if product.discount %}
            <span class="font-bold bg-orange-400 p-[1px] text-white mt-auto">Скидка {{ product.discount }} %</span>
            {% endif %}
            {% if product.image %}
            <img class='w-4/5 h-full object-cover block m-0-auto-1 text-center mb-4 max-[425px]:w-4/5 max-[425px]:object-contain' src="{{ product.image.url}}" alt="{{ product.name }}" />
            {% else %}
            {% comment %} если нет изображения {% endcomment %}
            <img class='w-4/5 h-full object-cover block m-0-auto-1 text-center mb-4 max-[425px]:w-4/5 max-[425px]:object-contain' src="{% static 'deps/images/not_images.png' %}" alt="Пицца" />
            {% endif %}
          </div>
          <div class="flex flex-col items-start grow p-5">
            <h3 class="m-0 mb-4 text-2xl font-bold text"><a href="{% url "menu:product" product.slug %}">{{ product.name }}</a></h3>
            <p class="mm-0 mb-4 text-slate-500">{{ product.description }}</p>
            <div class="flex justify-between items-center mt-auto w-full">
              {% if product.discount %}
              <s class=" text-orange-500"><p class="font-bold text-black mt-auto">{{ product.price }} ₽</p></s>
              <span><p class="font-bold text-black mt-auto text-center">{{product.sell_price}} ₽</p></span>
              {% else %}
                <p class="font-bold text-black mt-auto">{{ product.price }} ₽</p>
              {% endif %}
              <button class="p-0.5-1rem bg-orange-100 text-orange-600 hover:text-white border-none cursor-pointer rounded-md transition-bg  hover:bg-orange-400">В корзину</button>
            </div>
          </div>
        </article>
      </li>
    {% endfor %}
      </ul>
  </div>
</div>
      
{% endblock %}

goods/templates/goods/product.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
  <div class="max-w-6xl mx-auto  h-full flex flex-wrap py-6 px-6 xl:px-0 shadow-2xl rounded-[50px] ">
    <div class=" mb-6 lg:mb-0 lg:w-3/5 hover:scale-110">
        <!-- Изображение товара -->
        {% if product.discount %}
            <span class="font-bold bg-orange-400 p-[1px] text-white mt-auto">Скидка {{ product.discount }} %</span>
            {% endif %}
            {% if product.image %}
            <img class='rounded-xl w-4/5 m-0-auto-1' src="{{ product.image.url}}" alt="{{ product.name }}" />
            {% else %}
            {% comment %} если нет изображения {% endcomment %}
            <img class='rounded-xl w-4/5 m-0-auto-1' src="{% static 'deps/images/not_images.png' %}" alt="Пицца" />
            {% endif %}
    </div>
    <!-- Описание товара -->
    <div class="w-full lg:w-2/5 lg:p-6">
        <h3 class="flex m-0 mb-4 text-5xl max-[768px]:text-4xl max-[425px]:text-2xl font-bold text">{{ product.name }}</h3>
        <p class="flex m-0 mb-4 text-lg text-slate-500 max-[425px]:text-sm">{{ product.description }}</p>
        <div class="flex justify-between items-center  w-full">
          {% if product.discount %}
          <s class=" text-orange-500"><p class="font-bold text-xl text-black mt-auto max-[425px]:text-sm">{{ product.price }} ₽</p></s>
          <span><p class="font-bold text-lg text-black mt-auto text-center max-[425px]:text-sm">{{product.sell_price}} ₽</p></span>
          {% else %}
            <p class="font-bold text-lg text-black mt-auto">{{ product.price }} ₽</p>
          {% endif %}
          <button class="p-0.5-1rem text-lg bg-orange-100 text-orange-600 hover:text-white border-none cursor-pointer rounded-md transition-bg  hover:bg-orange-400 max-[425px]:text-sm">В корзину</button>
        </div>
    </div>
</div>


     
      
{% endblock %}

main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru" class='m-0 p-0 box-border'>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'deps/css/styles.css' %}" />
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'deps/favicon/apple-touch-icon.png' %}" />
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'deps/favicon/favicon-32x32.png' %}" />
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'deps/favicon/favicon-16x16.png' %}" />
    <link rel="manifest" href="{% static 'deps/favicon/site.webmanifest' %}" />
    <title>
      {% block title %}
        Pizza House
      {% endblock %}
    </title>
  </head>
  <body class='font-mono leading-4 flex flex-col min-h-screen'>
    {% comment %}шапка сайта{% endcomment %}
    <header class='bg-orange-500 py-3 px-0 p-1 '>
      {% comment %} fullscreen {% endcomment %}

      <nav class="max-lg:hidden">
        <div class="max-w-6xl mx-auto flex items-center justify-between">
          {% comment %} menu left {% endcomment %}
          <div class="flex items-center space-x-6">
            <a href="{% url 'main:index' %}" class="text-lg text-white font-extrabold">Pizza Home</a>
            <ul class='flex items-center text-black'>
              <li>
                <a class='p-0.5-1rem  hover:text-white' href="{% url 'goods:menu' %}">Меню</a>
              </li>
              <li>
                <a class='p-0.5-1rem  hover:text-white' href="{% url 'main:contact' %}">Контакты</a>
              </li>
            </ul>
          </div>
          {% comment %} menu right {% endcomment %}
          <div class="flex items-center space-x-4">
          <a href="#">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0 0 12 15.75a7.488 7.488 0 0 0-5.982 2.975m11.963 0a9 9 0 1 0-11.963 0m11.963 0A8.966 8.966 0 0 1 12 21a8.966 8.966 0 0 1-5.982-2.275M15 9.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
            </svg>            
          </a>
          <a href="#">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 3h1.386c.51 0 .955.343 1.087.835l.383 1.437M7.5 14.25a3 3 0 0 0-3 3h15.75m-12.75-3h11.218c1.121-2.3 2.1-4.684 2.924-7.138a60.114 60.114 0 0 0-16.536-1.84M7.5 14.25 5.106 5.272M6 20.25a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Zm12.75 0a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Z" />
            </svg>            
          </a>
        </div>
        </div>
      </nav>


        <nav id="mobile-menu" class="lg:hidden fixed left-0 top-0 right-0 bottom-0 items-center justify-center bg-orange-500 hidden">
          <div class='flex flex-col items-center gap-5 text-black'>
            <ul class='flex flex-col items-center gap-5 text-black'>
              <div class="flex">
                <a href="#">
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0 0 12 15.75a7.488 7.488 0 0 0-5.982 2.975m11.963 0a9 9 0 1 0-11.963 0m11.963 0A8.966 8.966 0 0 1 12 21a8.966 8.966 0 0 1-5.982-2.275M15 9.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
                  </svg>            
                </a>
             
              </div>
              <li>
                <a class='p-0.5-1rem  hover:text-white' href="{% url 'main:index' %}">Главная</a>
              </li>
              <li>
                <a class='p-0.5-1rem  hover:text-white' href="{% url 'goods:menu' %}">Меню</a>
              </li>
              <li>
                <a class='p-0.5-1rem  hover:text-white' href="{% url 'main:contact' %}">Контакты</a>
              </li>
            </ul>
            <div class="flex">

              <a href="#">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 3h1.386c.51 0 .955.343 1.087.835l.383 1.437M7.5 14.25a3 3 0 0 0-3 3h15.75m-12.75-3h11.218c1.121-2.3 2.1-4.684 2.924-7.138a60.114 60.114 0 0 0-16.536-1.84M7.5 14.25 5.106 5.272M6 20.25a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Zm12.75 0a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Z" />
                </svg>            
              </a>
            </div>
          </div>
        </nav>

        <div class="flex items-center justify-between lg:hidden">
          <a href="{% url 'main:index' %}" class="text-lg text-white font-extrabold pl-2">Pizza Home</a>
          
          <button id="burger" class="mr-6 group hidden relative h-5 w-[30px] max-lg:block">
            <span class="absolute bg-white h-[2px] w-full top-0 group-[.active]:translate-y-2 group-[.active]:rotate-45 transition-transform"></span>
            <span class="absolute bg-white h-[2px] w-full top-1/2 group-[.active]:opacity-0 transition-opacity"></span>
            <span class="absolute bg-white h-[2px] w-full bottom-0 group-[.active]:-translate-y-[10px] group-[.active]:-rotate-45 transition-transform"></span>
            </button>
        </div>


        

      {% comment %} {% block switch %}
      
        {% endblock %} {% endcomment %}
    </header>
    {% comment %}Создаем главный блок всего контента{% endcomment %}
    <main class='flex flex-[1] py-8 px-4 max-w-screen-xl my-0 mx-auto max-md:py-4 max-[425px]:py-4 max-[425px]:px-2'>
      {% block content %}

      {% endblock %}
    </main>
    {% comment %}нижняя часть страницы{% endcomment %}
    <footer class='bg-orange-500 text-white text-center w-full px-0 py-4'>
      <p>2024 Pizza Home. Все права защищены.</p>
    </footer>
    <script src='{% static "deps/js/burger.js" %}'></script>
  </body>
</html>

main/templates/main/contact.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} {{title}} {% endblock %}
{% block content %}
<h1>{{ title }}</h1>
<p>{{ about }}</p>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}
  {{ title }}
{% endblock %}

{% block content %}
  <div>

      <h1 class="text-center text-3xl font-bold max-md:text-xl max-[425px]:text-sm">{{ welcome }}</h1>
      <p class="text-center text-3xl font-bold max-md:text-xl max-[425px]:text-sm ">{{ about }}</p>


      <div class="max-w-[1200px] max-h-[900px] mt-2 overflow-hidden border-sky-100 max-md:max-w-[768px] max-md:max-h-[576px] max-md:ml-[10px] max-md:mr-[10px] max-[425px]:max-w-[425px] max-[425px]:max-h-[318px] ">
        
        <div class="w-full h-full border-solid border-[4px] border-orange-500">
          <img class="w-full h-full " src="{% static 'deps/images/image_1.jpg' %}" alt="изображение 1" />
          <img class="w-full h-full" src="{% static 'deps/images/image_2.jpg' %}" alt="изображение 2" />
          <img class="w-full h-full" src="{% static 'deps/images/image_3.jpg' %}" alt="изображение 3" />
        </div>
      </div>
    
      <script src='{% static 'deps/js/script.js' %}'>
      </script>

  </div>
{% endblock %}